### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by ollema** [DungFu/PowerRaid#1]
Hey!

Thanks for a great addon!

I think a really useful feature would be slash commands for some common checks.

For example:
`/powerraid check onycloak`
could trigger:
1. Scan for Raid Items
2. Report Raid Items (but with only Onyxia Scale Cloak selected, regardless of the setting in the GUI) to either the default report channel or for example the last used report channel/what is used in the GUI.

And another one would be:
`/powerraid check onycloakequipped`
could trigger:
1. Scan for Raid Items
2. Report Raid Items (but with only Onyxia Scale Cloak Equipped selected, regardless of the setting in the GUI) to either the default report channel or for example the last used report channel/what is used in the GUI.

This would allow you to keybind this to a macro to quickly check this before a pull or even incorporate this into any pull macros that you might have.

As for consumables, I think it makes sense to limit these slash command "checks" to the raid items only since there are so many different consumables. Or perhaps raid items only and protection potions since these are the only "required" items that you would want to check quickly before a pull.

I could see this being useful for Raid buffs as well. But then with fewer options, instead of `/powerraid check arcaneintellect` you would just do `/powerraid check buffs` and it would use the stored  "settings" for what buffs to check for and what kind of reporting to do.

Is this something that sounds interesting to you?

**Comment by DungFu** [comment]
This is a great idea! I can look into adding this (but it might require a bit of changes to the reporting code).

**Comment by DungFu** [comment]
I have added support for reporting raid buffs/world buffs/paladin buffs using console commands:
`/pr report (tab) (channel) (report_type)`

I am not going to release a new version right away since I want to test it to make sure everything is working and I didn't break everything :P

If you would like try it out, use download master branch from github and try it out in your addons folder. Let me know what you think :)

**Comment by ollema** [comment]
this is working great!

tried both raid buffs and world buffs but I could not test paladin buffs since I play horde.

**Comment by ollema** [comment]
actually, it seems that the GUI broke(?) after using some slash command:
![screenshot](https://gyazo.com/e6b7be747d825c55efba34d5cf857e22)

not sure how I undo this

**Comment by ollema** [comment]
for some reason, the slash command is also limited to `missing_each` now:
```
[PowerRaid] Invalid report type! Valid report types: missing_each
[PowerRaid] /pr report (raid_buffs, world_buffs, paladin_buffs) (channel) 
```

**Comment by ollema** [comment]
or maybe you are not supposed to be able to use any other `report_type` for `raid_buffs`?
```lua
function GetReportTypesOrder(tabId)
    if tabId == PowerRaidGUI.TalentsTabId then
        return {"invalid", "valid"}
    elseif tabId == PowerRaidGUI.RaidBuffsTabId or tabId == PowerRaidGUI.PaladinBuffsTabId then
        return {"missing_each"}
    else
        return {"has_all", "has_any", "missing_any", "missing_all", "has_each", "missing_each"}
    end
end
```
not sure when this changed if this is the case - since the video guide shows that you should be able to use any report type:
https://youtu.be/zL8NmSRb2RM?t=22

sorry for all the noise @DungFu

**Comment by DungFu** [comment]
Yea this was intended, I didn't think the other types for raid buffs would ever be useful

**Comment by ollema** [comment]
ah, I see.

no I agree, I was just a bit surprised.

then everything seems to be working for me! :)

**Comment by DungFu** [comment]
https://github.com/DungFu/PowerRaid/releases/tag/v3.2.3 has this feature added. I will look into adding support for more tabs
